export const bodyParts = [
  {
    image: require("../../assets/fitnessmodels/amrsshoulders.png"),
    name: "upper arms",
    text: "Arms",
  },
  {
    image: require("../../assets/fitnessmodels/fullbody.png"),
    name: "chest",
    text: "Chest",
  },

  {
    image: require("../../assets/fitnessmodels/back.png"),
    name: "back",
    text: "Back",
  },

  {
    image: require("../../assets/fitnessmodels/abss.png"),
    name: "waist",
    text: "Waist",
  },

  {
    image: require("../../assets/fitnessmodels/buttock.png"),
    name: "upper legs",
    text: "Legs",
  },

  {
    image: require("../../assets/fitnessmodels/fullbody.png"),
    name: "cardio",
    text: "Cardio",
  },
];

export const demoExercises = [
  {
    bodyPart: "upper arms",
    equipment: "assisted",
    gifUrl: "https://v2.exercisedb.io/image/oy2yWIOG0xsUoB",
    id: "0018",
    instructions: [
      "Stand with your feet shoulder-width apart and hold a towel with both hands behind your head.",
      "Keep your elbows close to your ears and your upper arms stationary.",
      "Slowly extend your forearms upward, squeezing your triceps at the top.",
      "Pause for a moment, then slowly lower the towel back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "assisted standing triceps extension (with towel)",
    secondaryMuscles: ["shoulders"],
    target: "triceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/p9gI6FBYPPhIiz",
    id: "0019",
    instructions: [
      "Adjust the machine to your desired weight and height.",
      "Kneel down on the pad facing the machine, with your hands gripping the handles.",
      "Lower your body by bending your elbows, keeping your back straight and close to the machine.",
      "Pause for a moment at the bottom, then push yourself back up to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "assisted triceps dip (kneeling)",
    secondaryMuscles: ["chest", "shoulders"],
    target: "triceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/5-qmBG8Td7nP9D",
    id: "0968",
    instructions: [
      "Stand with your feet shoulder-width apart and hold the band with an underhand grip, palms facing up.",
      "Keep your elbows close to your sides and slowly curl one arm up towards your shoulder, squeezing your biceps at the top.",
      "Lower the arm back down to the starting position and repeat with the other arm.",
      "Continue alternating arms for the desired number of repetitions.",
    ],
    name: "band alternating biceps curl",
    secondaryMuscles: ["forearms"],
    target: "biceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/u7vzA9LZHIWEfv",
    id: "0975",
    instructions: [
      "Place a band around your upper arms, just above the elbows.",
      "Assume a push-up position with your hands directly under your shoulders and your body in a straight line from head to heels.",
      "Bend your elbows and lower your chest towards the ground, keeping your elbows close to your sides.",
      "Push through your palms to extend your arms and return to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "band close-grip push-up",
    secondaryMuscles: ["chest", "shoulders"],
    target: "triceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/HQCGDEFKHdhAAi",
    id: "0976",
    instructions: [
      "Sit on a bench or chair with your legs spread apart and your feet flat on the ground.",
      "Hold one end of the band in your hand and step on the other end with your foot on the same side.",
      "Lean forward slightly and rest your elbow on the inside of your thigh, just above the knee.",
      "With your palm facing up, slowly curl your hand towards your shoulder, keeping your upper arm stationary.",
      "Pause for a moment at the top, then slowly lower your hand back down to the starting position.",
      "Repeat for the desired number of repetitions, then switch sides.",
    ],
    name: "band concentration curl",
    secondaryMuscles: ["forearms"],
    target: "biceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/opSZ4zyWYYC2Q6",
    id: "0986",
    instructions: [
      "Stand with your feet shoulder-width apart and place one end of the band under your foot.",
      "Hold the other end of the band with your arm fully extended overhead, palm facing forward.",
      "Keeping your upper arm stationary, curl your forearm towards your shoulder, squeezing your biceps.",
      "Pause for a moment at the top, then slowly lower your forearm back to the starting position.",
      "Repeat for the desired number of repetitions, then switch arms.",
    ],
    name: "band one arm overhead biceps curl",
    secondaryMuscles: ["forearms", "shoulders"],
    target: "biceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "band",
    gifUrl: "https://v2.exercisedb.io/image/-QKlAikIwQsBh-",
    id: "0998",
    instructions: [
      "Stand with your feet shoulder-width apart and hold the band with both hands, palms facing down.",
      "Extend your arms straight out to the sides, keeping them parallel to the ground.",
      "Slowly bend your elbows and bring your hands towards your shoulders, keeping your upper arms still.",
      "Pause for a moment, then slowly extend your arms back out to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "band side triceps extension",
    secondaryMuscles: ["shoulders"],
    target: "triceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/HiekVvxDFB0foU",
    id: "0023",
    instructions: [
      "Stand up straight with your feet shoulder-width apart and hold a barbell in each hand, palms facing forward.",
      "Keep your upper arms stationary and exhale as you curl the weights while contracting your biceps.",
      "Continue to raise the barbells until your biceps are fully contracted and the barbells are at shoulder level.",
      "Hold the contracted position for a brief pause as you squeeze your biceps.",
      "Inhale as you slowly begin to lower the barbells back to the starting position.",
      "Repeat for the desired number of repetitions, alternating arms.",
    ],
    name: "barbell alternate biceps curl",
    secondaryMuscles: ["forearms"],
    target: "biceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/cFIiTq6PUr4B2r",
    id: "2407",
    instructions: [
      "Stand up straight with your feet shoulder-width apart and hold a barbell with an underhand grip, palms facing up.",
      "Place your upper arms against the arm blaster, keeping your elbows close to your torso.",
      "Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.",
      "Continue to raise the barbell until your biceps are fully contracted and the bar is at shoulder level.",
      "Hold the contracted position for a brief pause as you squeeze your biceps.",
      "Inhale and slowly begin to lower the barbell back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell biceps curl (with arm blaster)",
    secondaryMuscles: ["forearms"],
    target: "biceps",
  },
  {
    bodyPart: "upper arms",
    equipment: "barbell",
    gifUrl: "https://v2.exercisedb.io/image/YJQ8AvfYXP3yQW",
    id: "0030",
    instructions: [
      "Lie flat on a bench with yout when the barbell touches your chest.",
      "Push the barbell back up to the starting position, fully extending your arms.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "barbell close-grip bench press",
    secondaryMuscles: ["chest", "shoulders"],
    target: "triceps",
  },
];
